// <auto-generated />
using System;
using DigitalGraduate.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalGraduate.Data.Migrations.ApplicationDbContextMigrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230327170708_AddedSpecialitiesAndGraduateProgramsModels")]
    partial class AddedSpecialitiesAndGraduateProgramsModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DigitalGraduate.Data.Models.Catalogs.GraduateProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GraduatePrograms");
                });

            modelBuilder.Entity("DigitalGraduate.Data.Models.Catalogs.ScientificSpeciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("TrainingAreaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingAreaId");

                    b.ToTable("ScientificSpecialities");
                });

            modelBuilder.Entity("DigitalGraduate.Data.Models.Catalogs.TrainingArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TrainingAreas");
                });

            modelBuilder.Entity("DigitalGraduate.Data.Models.Catalogs.ScientificSpeciality", b =>
                {
                    b.HasOne("DigitalGraduate.Data.Models.Catalogs.TrainingArea", "TrainingArea")
                        .WithMany()
                        .HasForeignKey("TrainingAreaId");

                    b.Navigation("TrainingArea");
                });
#pragma warning restore 612, 618
        }
    }
}
