// <auto-generated />
using System;
using DigitalGraduate.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalGraduate.Data.Migrations.ApplicationDbContextMigrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230621194632_AddedApiUserIdToStudent")]
    partial class AddedApiUserIdToStudent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DigitalGraduate.Data.Models.Catalogs.CertificateApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("ProvideTo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<bool>("WithOfficialSeal")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("CertificateApplications");
                });

            modelBuilder.Entity("DigitalGraduate.Data.Models.Catalogs.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("DigitalGraduate.Data.Models.Catalogs.GraduateProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GraduatePrograms");
                });

            modelBuilder.Entity("DigitalGraduate.Data.Models.Catalogs.Grant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GrantParticipation")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Grants");
                });

            modelBuilder.Entity("DigitalGraduate.Data.Models.Catalogs.Institute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cypher")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Institutes");
                });

            modelBuilder.Entity("DigitalGraduate.Data.Models.Catalogs.ScientificSpeciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("TrainingAreaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingAreaId");

                    b.ToTable("ScientificSpecialities");
                });

            modelBuilder.Entity("DigitalGraduate.Data.Models.Catalogs.TrainingArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TrainingAreas");
                });

            modelBuilder.Entity("DigitalGraduate.Data.Models.Catalogs.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsRegion")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("DigitalGraduate.Data.Models.Catalogs.UniversityEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<double>("Score")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("UniversityEvents");
                });

            modelBuilder.Entity("DigitalGraduate.Data.Models.UserData.GraduateStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApiUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("BudgetForm")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("Education")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<int>("FormOfStudy")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("InstituteId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("PassportData")
                        .HasColumnType("longtext");

                    b.Property<string>("Patronymic")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<int?>("ScientificSpecialityId")
                        .HasColumnType("int");

                    b.Property<int>("StudyStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("InstituteId");

                    b.HasIndex("ScientificSpecialityId");

                    b.ToTable("GraduateStudents");
                });

            modelBuilder.Entity("DigitalGraduate.Data.Models.Catalogs.CertificateApplication", b =>
                {
                    b.HasOne("DigitalGraduate.Data.Models.UserData.GraduateStudent", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DigitalGraduate.Data.Models.Catalogs.ScientificSpeciality", b =>
                {
                    b.HasOne("DigitalGraduate.Data.Models.Catalogs.TrainingArea", "TrainingArea")
                        .WithMany()
                        .HasForeignKey("TrainingAreaId");

                    b.Navigation("TrainingArea");
                });

            modelBuilder.Entity("DigitalGraduate.Data.Models.UserData.GraduateStudent", b =>
                {
                    b.HasOne("DigitalGraduate.Data.Models.Catalogs.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("DigitalGraduate.Data.Models.Catalogs.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId");

                    b.HasOne("DigitalGraduate.Data.Models.Catalogs.ScientificSpeciality", "ScientificSpeciality")
                        .WithMany()
                        .HasForeignKey("ScientificSpecialityId");

                    b.Navigation("Department");

                    b.Navigation("Institute");

                    b.Navigation("ScientificSpeciality");
                });
#pragma warning restore 612, 618
        }
    }
}
